## Demo 2: Logic Functions

In this demo, you will be shown how to create arrays and perform logic functions on them.

### Question : Create 1-D array of 20 evenly spaced element between 1 and 100

In [3]:
#Create an array using linspace()
x = np.linspace(1, 100, 20)

#Print an array 
print(x)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


### Question :Create two random array A and B
a] check whether both the arrays are equal
b] Test the type of array element-wise
c] Compare two arrays element-wise
   So here random array is generated using numpy.random.randint(low, high, size)
   It is one of the function for generating random elements in array
   It returns an array of specified shape and fills it with random integers from low to high (exclusive), i.e. in the interval    of(low, high)

In [4]:
#Create two random array between 0 to 100 with 5 elements each
A = np.random.randint(0,100,5)
B = np.random.randint(0,100,5)

In [5]:
A

array([12, 25, 32, 82, 91])

In [6]:
B

array([78, 89, 70, 15, 29])

In [7]:
#Check whether both the elements are equal
x = np.equal(A,B)
print(x)

[False False False False False]


In [8]:
#Test the type of array element-wise for real number
np.isreal(A)

array([ True,  True,  True,  True,  True])

In [9]:
#Test the type of array element-wise for complex number
np.iscomplex(B)

array([False, False, False, False, False])

In [10]:
#Compare if A is greater than B element-wise
np.greater(A,B)

array([False, False, False,  True,  True])

In [11]:
#Compare if A is lesser than B element-wise
np.less(A,B)

array([ True,  True,  True, False, False])

#### Conclusion: This code demonstrates how to create arrays in numpy and how to use different logic functions