In [1]:
import numpy as np

In [81]:
a = np.array([4,3,20])

b = np.array([[11,9],[8,17],[2,17]])

a
b


array([[11,  9],
       [ 8, 17],
       [ 2, 17]])

In [79]:
c = np.dot(a,b)
c

array([68, 87])

In [65]:
# Perform encryption using mod func.

h = np.mod(c,26)
print("h:", h)

h: [[16  9]]


In [77]:
e = np.array([20,17])
e

array([20, 17])

In [75]:
f = np.dot(e,b)
f

array([356, 469])

In [87]:
h1 = np.mod(f,26)
print("h1:",h1)

h1: [18  1]


In [73]:
g = np.array([4,10])
g

array([ 4, 10])

In [71]:
i = np.dot(g,b)
i

array([124, 206])

In [83]:
h2 = np.mod(g,26)
print("h2:",h2)

h2: [ 4 10]


In [91]:
h, h1, h2

(array([[16,  9]], dtype=int32),
 array([18,  1], dtype=int32),
 array([ 4, 10], dtype=int32))