# Mathematical operations of numpy array
- Mathematical operators: +,-, * ,/,**


In [2]:
import numpy as np

In [3]:
numpy_array1 = np.array([10,20,30,40,50])
numpy_array2 = np.array([5,2,3,4,1])

In [4]:
#addition 
numpy_array1 + numpy_array2

array([15, 22, 33, 44, 51])

In [5]:
# subtraction 
numpy_array1 - numpy_array2

array([ 5, 18, 27, 36, 49])

In [6]:
# multiplication 

numpy_array1 * numpy_array2

array([ 50,  40,  90, 160,  50])

In [7]:
#division

numpy_array1 / numpy_array2

array([ 2., 10., 10., 10., 50.])

In [8]:
# exponentiation

numpy_array1 ** numpy_array2

array([ 100000,     400,   27000, 2560000,      50])

# Broadcasting in numpy arrays

In [9]:
print(numpy_array1)

[10 20 30 40 50]


In [10]:
numpy_array1 * 2

array([ 20,  40,  60,  80, 100])

In [11]:
numpy_array1 + 2

array([12, 22, 32, 42, 52])

In [12]:
numpy_array1 / 10

array([1., 2., 3., 4., 5.])

In [13]:
numpy_array1 - 2.5

array([ 7.5, 17.5, 27.5, 37.5, 47.5])

In [14]:
numpy_array1 ** 2

array([ 100,  400,  900, 1600, 2500])

# Sorting numpy arrays
- sort() , argsort()

In [15]:
numpy_array2 = np.array([5,2,3,4,1])
print(numpy_array2)

[5 2 3 4 1]


In [16]:
# sort() method would return the values of the input array in the ascending order
print(np.sort(numpy_array2))

[1 2 3 4 5]


Note:
- numpy sort() method doesn't allow sorting in descending order.     

In [17]:
# interviewer asks you to sort the numpy array in descending order

inp_array = np.array([90,200,8,4,1000])

print(np.sort(inp_array))
sorted_arr = np.sort(inp_array)
print("------------------")
descending_arr = sorted_arr[::-1] 
# we use ::-1 slicing value to reverse a list in Python
print(descending_arr)

[   4    8   90  200 1000]
------------------
[1000  200   90    8    4]


In [18]:
print(numpy_array2)
print(np.argsort(numpy_array2))

[5 2 3 4 1]
[4 1 2 3 0]


In [20]:
import datetime

right_now = datetime.datetime.now()
formatted_str = right_now.strftime("%d-%m-%Y %H:%M:%S")
print("Formatted date & time:", formatted_str)


formatted_str =right_now.strftime("%d-%m-%Y %H:%M:%S") # wrong one
print("formatted_str:", right_now)  # wrong code 

Formatted date & time: 20-06-2024 16:20:38
formatted_str: 2024-06-20 16:20:38.947374


Note:

- argsort() would sort the elements of the input array in ascending order and return the index values of the sorted elements of the input array in the ascending order by default

Python is a dynamically typed programming language. 

# End of session